### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by mousaique** [nhthn/supercollider-automation#6]
Hi,

I've tried building it via terminal but got the following error. Is this due to some incompatibility (because of M1?) or maybe I overlooked something?

jan@Jans-MBP-2 build % cmake --build . --config Release   

[ 33%] Building CXX object CMakeFiles/Automation_scsynth.dir/plugins/Automation/Automation.cpp.o

clang: error: the clang compiler does not support '-march=native'

make[2]: *** [CMakeFiles/Automation_scsynth.dir/plugins/Automation/Automation.cpp.o] Error 1

make[1]: *** [CMakeFiles/Automation_scsynth.dir/all] Error 2

make: *** [all] Error 2

jan@Jans-MBP-2 build % 

Appreciate any advice, thank you for this contribution!

**Comment by nhthn** [comment]
I can't really provide much support for this repo, it was freelance work for a client and I'm not planning on maintaining it as a hobby. That said, this seems like a simple fix: try `cmake .. -DNATIVE=OFF`.

**Comment by mousaique** [comment]
i see, thanks for pointing out. it seems to have worked, and is working in SC now!
thank you for this valuable UGen!

jan@Jans-MBP-2 build % cmake .. -DNATIVE=OFF
-- Found SuperCollider: /Users/jan/Downloads/auto/supercollider
-- Building plugins for SuperCollider version: 3.14.0-dev
-- Install directory set to: /Users/jan/Downloads/auto/supercollider-automation/build/install
-- Added server plugin target Automation_scsynth
-- Generating plugin targets done
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/jan/Downloads/auto/supercollider-automation/build
jan@Jans-MBP-2 build % cmake --build . --config Release --target install
[ 33%] Building CXX object CMakeFiles/Automation_scsynth.dir/plugins/Automation/Automation.cpp.o
[ 66%] Building CXX object CMakeFiles/Automation_scsynth.dir/core/automation_core.cpp.o
[100%] Linking CXX shared module Automation_scsynth.scx
[100%] Built target Automation_scsynth
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/jan/Downloads/auto/supercollider-automation/build/install/Automation/Automation/Automation_scsynth.scx
-- Installing: /Users/jan/Downloads/auto/supercollider-automation/build/install/Automation/Automation/Classes/Automation.sc
-- Installing: /Users/jan/Downloads/auto/supercollider-automation/build/install/Automation/Automation/HelpSource/Classes/Automation.schelp
jan@Jans-MBP-2 build %
